In [206]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols, solve

# Functions

In [207]:
def getMinorEntry(matrix, row, col):
    n = matrix.shape[0]
    minor = np.zeros((n-1, n-1), dtype=object)
    rowIdx = 0
    for i in range(n):
        colIdx = 0
        if (i != row):
            for j in range(n):
                if (j != col):
                    minor[rowIdx, colIdx] = matrix[i, j]
                    colIdx += 1
            rowIdx += 1
    
    return getDeterminant(minor)

def getDeterminant(matrix):
    if (matrix.shape[0] == 1):
        return matrix[0, 0]
    elif (matrix.shape[0] == 2):
        return(matrix[0, 0]*matrix[1, 1] - (matrix[0, 1]*matrix[1, 0]))
    else:
        determinant = 0
        sign = 1
        for j in range(matrix.shape[1]):
            determinant += matrix[0, j]*getMinorEntry(matrix, 0, j)*sign
            sign *= -1;
    return determinant

def getEigenVal(matrix):
    mcopy = matrix.copy()
    x = symbols('x')
    nshape = mcopy.shape[0]
    lambdaId = np.eye(nshape)*x - mcopy

    expr = getDeterminant(lambdaId)
    val = solve(expr)

    # Ambil value unik saja
    val = [np.float(x) for x in set(val)]
    return val

# Singular Value Decomposition 

### Important functions:

### * np.zeros -> make n x m matrix filled with 0
### * np.fill_diagonal -> fill diagonal without changing matrix shape
### * symbol() and solve() in sympy -> solving equation

In [208]:
mat = np.array([[3, 1, 1],
                [-1, 3, 1]], dtype=float)
mshape = mat.shape
mat

array([[ 3.,  1.,  1.],
       [-1.,  3.,  1.]])

In [209]:
ushape = (mshape[0], mshape[0])
vshape = (mshape[1], mshape[1])
#sigma shape = mshape
sigmaVal = [0 for i in range(min(mshape))]

In [210]:
#Langkah 1: Singular Kiri
ski = np.matmul(mat, mat.T)
ska = np.matmul(mat.T, mat)
ska

array([[10.,  0.,  2.],
       [ 0., 10.,  4.],
       [ 2.,  4.,  2.]])

In [211]:
#Ubah jadi matriks upper triangular gunakan OBE
print(np.linalg.eigvals(ska), np.linalg.eigvals(ski))
print(getEigenVal(ska), getEigenVal(ski))

[ 0. 10. 12.] [12. 10.]
[10.0, 0.0, 12.0] [10.0, 12.0]
